"""path column

Revision ID: fb5d6f18237d
Revises: 1f19cbc97aee
Create Date: 2025-06-26 00:53:08.352237

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb5d6f18237d"
down_revision: Union[str, Sequence[str], None] = "1f19cbc97aee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_metadata", sa.Column("path", sa.String(), nullable=False))
    op.create_index(op.f("ix_file_metadata_path"), "file_metadata", ["path"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_metadata_path"), table_name="file_metadata")
    op.drop_column("file_metadata", "path")
    # ### end Alembic commands ###
