"""removed column

Revision ID: 1f19cbc97aee
Revises: 9e54ba0246cc
Create Date: 2025-06-22 03:05:48.501790

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f19cbc97aee"
down_revision: Union[str, Sequence[str], None] = "9e54ba0246cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_metadata", sa.Column("extension", sa.String(), nullable=False))
    op.drop_column("file_metadata", "path")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_metadata", sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("file_metadata", "extension")
    # ### end Alembic commands ###
